/**
 * Données de démo — équivalent des tables MySQL (categorie, gamme, produit, magasin).
 * Remplace le back-end PHP / mysqli pour la version HTML statique.
 */
window.FM_DATA = {
  categories: [
    { id: 1, libelle: "Salon" },
    { id: 2, libelle: "Chambre" },
    { id: 3, libelle: "Salle à manger" },
    { id: 4, libelle: "Bureau" },
    { id: 5, libelle: "Entrée" },
    { id: 6, libelle: "Extérieur" },
    { id: 7, libelle: "Rangement" },
  ],
  gammes: [
    { id: 1, libelle: "Essentiel" },
    { id: 2, libelle: "Confort" },
    { id: 3, libelle: "Premium" },
    { id: 4, libelle: "Scandinave" },
    { id: 5, libelle: "Design" },
    { id: 6, libelle: "Eco-responsable" },
    { id: 7, libelle: "Pro" },
  ],
  magasins: [
    {
      code: "PAR01",
      nom: "France-Mobilier Paris Bastille",
      adresse: "12 rue de la Roquette",
      cpVille: "75011 Paris",
    },
    {
      code: "LYO01",
      nom: "France-Mobilier Lyon Part-Dieu",
      adresse: "45 cours Lafayette",
      cpVille: "69003 Lyon",
    },
    {
      code: "MAR01",
      nom: "France-Mobilier Marseille",
      adresse: "8 la Canebière",
      cpVille: "13001 Marseille",
    },
  ],
  produits: [
    { id: 1, reference: "SL-CAN-01", designation: "Canapé 3 places tissu gris", prixTTC: 599.9, photo: "canape", categorie: 1, gamme: 2 },
    { id: 2, reference: "SL-TAB-02", designation: "Table basse chêne massif", prixTTC: 249.0, photo: "tablebasse", categorie: 1, gamme: 3 },
    { id: 3, reference: "SL-BIB-03", designation: "Bibliothèque 5 niveaux blanc", prixTTC: 189.5, photo: "biblio", categorie: 1, gamme: 1 },
    { id: 4, reference: "CH-LIT-01", designation: "Lit 160×200 avec tête de lit", prixTTC: 449.0, photo: "lit", categorie: 2, gamme: 2 },
    { id: 5, reference: "CH-ARM-02", designation: "Armoire 2 portes miroir", prixTTC: 379.0, photo: "armoire", categorie: 2, gamme: 1 },
    { id: 6, reference: "CH-COM-03", designation: "Commode 6 tiroirs chêne", prixTTC: 299.0, photo: "commode", categorie: 2, gamme: 4 },
    { id: 7, reference: "SA-TAB-01", designation: "Table à manger 6 personnes", prixTTC: 529.0, photo: "tablesam", categorie: 3, gamme: 3 },
    { id: 8, reference: "SA-CHA-02", designation: "Lot de 4 chaises velours", prixTTC: 320.0, photo: "chaises", categorie: 3, gamme: 2 },
    { id: 9, reference: "SA-BUF-03", designation: "Buffet 3 portes laqué blanc", prixTTC: 410.0, photo: "buffet", categorie: 3, gamme: 4 },
    { id: 10, reference: "BU-BUR-01", designation: "Bureau plateau 140 cm + caisson", prixTTC: 289.0, photo: "bureau", categorie: 4, gamme: 1 },
    { id: 11, reference: "BU-FAU-02", designation: "Fauteuil de bureau ergonomique", prixTTC: 199.0, photo: "fauteuil", categorie: 4, gamme: 2 },
    { id: 12, reference: "BU-ETG-03", designation: "Étagère murale 3 tablettes", prixTTC: 79.9, photo: "etagere", categorie: 4, gamme: 1 },
    { id: 13, reference: "SL-CAN-04", designation: "Canapé d'angle modulable anthracite", prixTTC: 899.0, photo: "canape", categorie: 1, gamme: 3 },
    { id: 14, reference: "SL-TAB-05", designation: "Table basse relevable rangement intégré", prixTTC: 329.0, photo: "tablebasse", categorie: 1, gamme: 2 },
    { id: 15, reference: "SL-BIB-06", designation: "Meuble TV bibliothèque combiné", prixTTC: 519.0, photo: "biblio", categorie: 1, gamme: 4 },
    { id: 16, reference: "CH-LIT-04", designation: "Lit coffre 140×190 avec sommier", prixTTC: 699.0, photo: "lit", categorie: 2, gamme: 3 },
    { id: 17, reference: "CH-ARM-05", designation: "Dressing 3 portes coulissantes", prixTTC: 649.0, photo: "armoire", categorie: 2, gamme: 2 },
    { id: 18, reference: "CH-COM-06", designation: "Chevet design 2 tiroirs (lot de 2)", prixTTC: 159.0, photo: "commode", categorie: 2, gamme: 1 },
    { id: 19, reference: "SA-TAB-04", designation: "Table extensible 8/10 couverts", prixTTC: 799.0, photo: "tablesam", categorie: 3, gamme: 3 },
    { id: 20, reference: "SA-CHA-05", designation: "Lot de 6 chaises tissu bouclette", prixTTC: 449.0, photo: "chaises", categorie: 3, gamme: 4 },
    { id: 21, reference: "SA-BUF-06", designation: "Buffet haut 4 portes finition noyer", prixTTC: 729.0, photo: "buffet", categorie: 3, gamme: 3 },
    { id: 22, reference: "BU-BUR-04", designation: "Bureau assis-debout électrique 120 cm", prixTTC: 599.0, photo: "bureau", categorie: 4, gamme: 3 },
    { id: 23, reference: "BU-FAU-05", designation: "Chaise de bureau mesh avec appui-tête", prixTTC: 259.0, photo: "fauteuil", categorie: 4, gamme: 2 },
    { id: 24, reference: "BU-ETG-06", designation: "Bibliothèque bureau 6 niches métal/bois", prixTTC: 239.0, photo: "etagere", categorie: 4, gamme: 4 },
    { id: 25, reference: "EN-CON-01", designation: "Console d'entrée métal noir et bois", prixTTC: 199.0, photo: "tablebasse", categorie: 5, gamme: 5 },
    { id: 26, reference: "EN-POR-02", designation: "Porte-manteau sur pied avec étagère", prixTTC: 89.9, photo: "etagere", categorie: 5, gamme: 1 },
    { id: 27, reference: "EN-BAN-03", designation: "Banc d'entrée avec coffre chaussures", prixTTC: 149.0, photo: "commode", categorie: 5, gamme: 2 },
    { id: 28, reference: "EX-SAL-01", designation: "Salon de jardin 4 places résine tressée", prixTTC: 799.0, photo: "canape", categorie: 6, gamme: 3 },
    { id: 29, reference: "EX-TAB-02", designation: "Table extérieure pliante 6 couverts", prixTTC: 299.0, photo: "tablesam", categorie: 6, gamme: 6 },
    { id: 30, reference: "EX-CHS-03", designation: "Lot de 4 chaises outdoor empilables", prixTTC: 179.0, photo: "chaises", categorie: 6, gamme: 1 },
    { id: 31, reference: "RG-ARM-01", designation: "Armoire multi-usages 4 tablettes", prixTTC: 269.0, photo: "armoire", categorie: 7, gamme: 7 },
    { id: 32, reference: "RG-MOD-02", designation: "Module de rangement 9 cases", prixTTC: 139.0, photo: "biblio", categorie: 7, gamme: 4 },
    { id: 33, reference: "RG-BUF-03", designation: "Buffet bas rangement compact", prixTTC: 319.0, photo: "buffet", categorie: 7, gamme: 5 },
  ],
};
